# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_ADAPTER_PROTOCOL) += adapter_protocol.o

obj-$(CONFIG_ADAPTER_PROTOCOL_FCP) += adapter_protocol_fcp/
obj-$(CONFIG_ADAPTER_PROTOCOL_SCP) += adapter_protocol_scp/
obj-$(CONFIG_ADAPTER_PROTOCOL_PD) += adapter_protocol_pd/
obj-$(CONFIG_ADAPTER_PROTOCOL_UVDM) += adapter_protocol_uvdm/
obj-$(CONFIG_ADAPTER_PROTOCOL_UFCS) += adapter_protocol_ufcs/
