# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_WIRELESS_STWLC68) += stwlc68.o
obj-$(CONFIG_WIRELESS_STWLC68) += stwlc68_fw.o
obj-$(CONFIG_WIRELESS_STWLC68) += stwlc68_qi.o
obj-$(CONFIG_WIRELESS_STWLC68) += stwlc68_tx.o
obj-$(CONFIG_WIRELESS_STWLC68) += stwlc68_dts.o
obj-$(CONFIG_WIRELESS_STWLC68) += stwlc68_rx.o
