# SPDX-License-Identifier: GPL-2.0
#
# huawei coul drivers
#

obj-$(CONFIG_HUAWEI_COUL) += coul_interface.o
obj-$(CONFIG_HUAWEI_COUL) += coul_test.o
obj-$(CONFIG_HUAWEI_COUL) += coul_sysfs.o
obj-y += coul_calibration.o
