# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_HUAWEI_POWER_SUPPLY_APPLICATION) += power_supply_application.o
obj-$(CONFIG_POWER_SUPPLY) += power_supply_interface.o
obj-$(CONFIG_HUAWEI_POWER_SUPPLY) += power_supply.o
