# SPDX-License-Identifier: GPL-2.0
obj-y += charger_common_interface.o

obj-$(CONFIG_DIRECT_CHARGER) += direct_charge_error_handle.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charge_ic_manager.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charge_comp.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charge_ic_interface.o
obj-$(CONFIG_DIRECT_CHARGER) += multi_ic_check.o
obj-$(CONFIG_DIRECT_CHARGER) += direct_charge_ic.o
