# huawei gadget Class Driver
obj-$(CONFIG_HW_GADGET) += hw_usb_rwswitch.o
obj-$(CONFIG_HW_GADGET) += hw_usb_sync_host_time.o
obj-$(CONFIG_HW_GADGET) += hw_usb_handle_pcinfo.o
obj-$(CONFIG_HW_GADGET) += hw_controlrequest_handle.o
