# SPDX-License-Identifier: GPL-2.0
#
# huawei battery drivers
#

obj-$(CONFIG_HUAWEI_BATTERY_MODEL) += battery_model/
obj-$(CONFIG_HUAWEI_BATTERY_UI_CAPACTIY) += battery_ui_capacity/
obj-$(CONFIG_HUAWEI_BATTERY_FAULT) += battery_fault/
obj-$(CONFIG_HUAWEI_BATTERY_SOH) += battery_soh/
obj-$(CONFIG_HUAWEI_BATTERY_TEMP) += battery_temp/
obj-$(CONFIG_HUAWEI_BATTERY_TYPE_IDENTIFY) += battery_type_identify/
obj-$(CONFIG_HUAWEI_BATTERY_1S2P) += battery_1s2p/

obj-$(CONFIG_HUAWEI_BATTERY_CORE) += battery_core.o
obj-$(CONFIG_HUAWEI_MIXED_BATT) += huawei_mixed_battery.o
