# Copyright (c) Huawei Technologies Co., Ltd. 2017-2021. All rights reserved.
#
# Makefile for the EMUI Integrity Measurement Architecture(EIMA).
#

obj-$(CONFIG_HUAWEI_EIMA) += eima_module.o eima_queue.o eima_fs.o dkm.o hash_generator.o
ifndef CONFIG_TEE_ANTIROOT_CLIENT
obj-$(CONFIG_HUAWEI_EIMA) += eima_check.o
endif
obj-$(CONFIG_HUAWEI_EIMA_ACCESS_CONTROL) += eima_netlink.o
ifdef CONFIG_MTK_PLATFORM
ccflags-$(CONFIG_TEE_ANTIROOT_CLIENT) += -Idrivers/ca_antiroot
else
ccflags-$(CONFIG_TEE_ANTIROOT_CLIENT) += -Idrivers/hisi/ca_antiroot
endif

flags += -Wdate-time -Wfloat-equal
