obj-y += chipone.o
chipone-objs += cts_core.o cts_efctrl.o cts_emb_flash.o cts_firmware.o cts_test.o  cts_strerror.o cts_tool.o
chipone-objs += cts_plat_huawei_tskit.o chipone_tskit_ops.o

EXTRA_CFLAGS += -I$(srctree)/drivers/hisi/tzdriver
EXTRA_CFLAGS += -I$(srctree)/drivers/tzdriver
EXTRA_CFLAGS += -I$(srctree)/drivers/devkit/lcdkit/lcdkit3.0/kernel/common/include
EXTRA_CFLAGS += -I$(srctree)/drivers/devkit/tpkit/3_0