#ifndef _LCD_BL_LINEAR_EXPONENTIAL_TABLE_H_
#define _LCD_BL_LINEAR_EXPONENTIAL_TABLE_H_

#define LCD_BL_LINEAR_EXPONENTIAL_TABLE_NUM  2048
extern unsigned int linear_exponential_table[LCD_BL_LINEAR_EXPONENTIAL_TABLE_NUM];
#endif