# SPDX-License-Identifier: GPL-2.0
#
# huawei power common drivers
#

ifeq ($(HLTHERM_RUNTEST), true)
CFLAGS_KERNEL += -DCONFIG_HLTHERM_RUNTEST
endif

obj-y += cc_common_module/
obj-y += cc_adapter/
obj-y += cc_protocol/
obj-y += cc_coul/
obj-y += cc_hardware_ic/
obj-y += cc_hardware_monitor/
obj-y += cc_hardware_channel/
obj-y += cc_battery/
obj-y += cc_charger/
obj-y += cc_accessory/