# Makefile for the irda drivers.
#

# Each configuration option enables a list of files.
#obj-$(CONFIG_CYPRESS_TS_KIT)  += cypress/
obj-$(CONFIG_HUAWEI_ROTARY_CROWN)  += rotary_crown/
#ifeq ($(CONFIG_HUAWEI_TS_TEST),y)
#EXTRA_CFLAGS += -DHUAWEI_TOUCHSCREEN_TEST
#endif
#EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
