ccflags-y += -Wall -Werror
ccflags-y  += -I$(srctree)/drivers/huawei_platform/mntn/blackbox/include

obj-$(CONFIG_HUAWEI_BB) += rdr_init.o
obj-$(CONFIG_HUAWEI_BB) += rdr_storage_api.o
obj-$(CONFIG_HUAWEI_BB) += rdr_storage_device.o
obj-$(CONFIG_HUAWEI_BB) += rdr_file_device.o
obj-$(CONFIG_HUAWEI_BB) += ramparser/rdr_dmesg.o
obj-$(CONFIG_HUAWEI_BB) += ramparser/rdr_freq.o
obj-$(CONFIG_HUAWEI_BB) += ramparser/rdr_diaginfo.o
obj-$(CONFIG_HUAWEI_BB) += ramparser/rdr_fulldump.o
