obj-$(CONFIG_MCU_TS) += mcu.o
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
EXTRA_CFLAGS += -Idrivers/huawei_platform/sensor/ext_inputhub/default/
EXTRA_CFLAGS += -Idrivers/devkit/tpkit
