obj-$(CONFIG_ILITEK_TS_KIT_3_0) += ilitek.o \
	ilitek_dts.o \
	ilitek_hostdl.o \
	ilitek_ic.o \
	ilitek_node.o \
	ilitek_spi.o \
	ilitek_mp.o \
	ilitek_tddi_ts.o \
	ilitek_touch.o \

EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
EXTRA_CFLAGS += -Idrivers/devkit/lcdkit/lcdkit3.0/kernel/common/include
EXTRA_CFLAGS += -Idrivers/devkit/tpkit/3_0
EXTRA_CFLAGS += -Itechpack/display
EXTRA_CFLAGS += -Itechpack/display/msm/dsi
