# SPDX-License-Identifier: GPL-2.0
#
# huawei hardware monitor drivers
#

obj-$(CONFIG_HUAWEI_VBUS_MONITOR) += vbus_monitor/
obj-$(CONFIG_HUAWEI_LGA_CHECK) += lga_check/
obj-$(CONFIG_HUAWEI_WATER_DETECT) += water_detect/
obj-$(CONFIG_HUAWEI_SOC_CONTROL) += soc_control/
obj-$(CONFIG_HUAWEI_BAT_HEATING) += bat_heating/
obj-$(CONFIG_HUAWEI_TEMP_CONTROL) += temp_control/
obj-$(CONFIG_HUAWEI_BATT_ACR_DETECT) += acr_detect/
obj-$(CONFIG_HUAWEI_BTB_CHECK) += btb_check/
obj-$(CONFIG_HUAWEI_SOC_DECIMAL) += soc_decimal/
obj-$(CONFIG_HUAWEI_CPU_BUCK) += cpu_buck/
obj-$(CONFIG_HUAWEI_FFC_CONTROL) += ffc_control/
obj-$(CONFIG_HUAWEI_SMPL) += smpl/
obj-$(CONFIG_HUAWEI_USB_SHORT_CIRCUIT_PROTECT) += uscp/
obj-$(CONFIG_HUAWEI_WATER_CHECK) += water_check/
obj-$(CONFIG_HUAWEI_SHIP_MODE) += ship_mode/
