obj-$(CONFIG_WIRELESS_CHARGER) += wireless_charger.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_charge_dts.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_charge_psy.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_charge_ictrl.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_direct_charge/
