# ELAN
obj-$(CONFIG_ELAN_TS_KIT) += elan_ts.o
obj-$(CONFIG_ELAN_TS_KIT) += elan_mmi.o
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
EXTRA_CFLAGS += -Idrivers/devkit/tpkit
EXTRA_CFLAGS += -Idrivers/devkit/lcdkit/lcdkit1.0/include
