obj-y += huawei_charger_adaptor.o
obj-y += charger/
obj-y += hardware_ic/
obj-y += battery/

obj-$(CONFIG_HUAWEI_KSTATE) += hw_kstate/
obj-$(CONFIG_HUAWEI_FEATURE_PRINT_PID_NAME) += pid_socket/
obj-$(CONFIG_HUAWEI_DUBAI) += dubai/