# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_HUAWEI_POWER_GLINK) += power_glink.o
obj-$(CONFIG_HUAWEI_POWER_GLINK) += power_glink_debug.o
obj-$(CONFIG_HUAWEI_POWER_GLINK) += power_glink_handle_charge.o
obj-$(CONFIG_HUAWEI_POWER_GLINK) += power_glink_handle_usb.o
