# In case the platform does NOT support this type of sensors

obj-y	+= ap_sensor_channel.o
obj-y	+= ap_sensor_route.o
obj-y	+= ap_motion_route.o
obj-y	+= ap_motion_channel.o
obj-y	+= ar_sensor_channel.o
obj-y	+= ar_sensor_route.o
obj-y	+= smart_ar.o
obj-y	+= smart_flp.o
obj-y	+= smart_flp_dt.o
obj-y	+= smart_softtimer.o
