subdir-ccflags-y += -Werror -I$(srctree)/drivers/usb/gadget
subdir-ccflags-y += -Werror -I$(srctree)/drivers/usb/gadget/function

obj-$(CONFIG_HWUSB_F_MTP) += f_mtp.o
obj-$(CONFIG_HWUSB_F_PTP) += f_ptp.o
