#
# Makefile for misc devices that really don't fit anywhere else.
#
obj-$(CONFIG_HW_COMB_KEY) += power_key_event.o
obj-$(CONFIG_HW_COMB_KEY) += volume_key_event.o
obj-$(CONFIG_HW_COMB_KEY) += comb_key.o