# SPDX-License-Identifier: GPL-2.0
#
# huawei hardware ic drivers
#

obj-$(CONFIG_BUCKBOOST) += buck_boost/
obj-$(CONFIG_CHARGE_PUMP) += charge_pump/
obj-$(CONFIG_LOADSWITCH) += load_switch/
obj-$(CONFIG_SWITCHCAP) += switch_capacitor/
obj-$(CONFIG_BOOST_5V) += boost_5v/
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_charge_ic/
obj-$(CONFIG_CHARGE_ADC_MONITOR) += charge_adc_monitor/
obj-$(CONFIG_FUEL_GAUGE) += fuel_gauge/
obj-$(CONFIG_ADAPTER_PROTOCOL) += protocol_ic/
