# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_power_supply.o
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_firmware.o

obj-$(CONFIG_WIRELESS_CHARGER) += wireless_test/
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_rx/
obj-$(CONFIG_WIRELESS_CHARGER) += wireless_tx/
obj-$(CONFIG_WIRELESS_ACCESSORY) += wireless_accessory/
