# Makefile for the irda drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_GOODIX_GT1X_TS_KIT_3_0) += gt1x/
obj-$(CONFIG_SYNAPTICS_TS_KIT_3_0)  += synaptics/
obj-$(CONFIG_GOODIX_GTX8_TS_KIT)  += gt8x/
obj-$(CONFIG_SAMSUNG_TS_KIT_3_0)  += samsung/
obj-$(CONFIG_SYNAPTICS_TCM_TS_KIT_3_0)  += synaptics_tcm/
obj-$(CONFIG_FOCAL_TS_KIT_3_0)  += focaltech/
obj-$(CONFIG_NOVATEK_TS_KIT_3_0)  += novatek/
obj-$(CONFIG_ST_TS_KIT_3_0)  += st/
obj-$(CONFIG_PARADE_TS_KIT_3_0)  += parade/
obj-$(CONFIG_ATMEL_TS_KIT_3_0)  += atmel/
obj-$(CONFIG_ELAN_TS_KIT_3_0)  += elan/
obj-$(CONFIG_MSTAR_TS_KIT_3_0)  += mstar/
obj-$(CONFIG_GOODIX_GTX8_BRL_TS_KIT_3_0) += gtx8_brl/
obj-$(CONFIG_HIMAX_TS_KIT_3_0)  += himax_64/
obj-$(CONFIG_ILITEK_TS_KIT_3_0) +=ilitek/
obj-$(CONFIG_CHIPONE_TS_KIT_3_0) += chipone/
obj-$(CONFIG_ZINITIX_TS_KIT_3_0) +=zinitix/
obj-$(CONFIG_CHIPONE_HYBRID_TS_KIT_3_0) += chipone_hybrid/
#ifeq ($(CONFIG_HUAWEI_TS_TEST_3_0),y)
#EXTRA_CFLAGS += -DHUAWEI_TOUCHSCREEN_TEST
#endif
#EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
