# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_PROTOCOL_IC_SC200X) += sc200x.o
obj-$(CONFIG_PROTOCOL_IC_SC200X) += sc200x_i2c.o
obj-$(CONFIG_PROTOCOL_IC_SC200X) += sc200x_tcpc.o
obj-$(CONFIG_PROTOCOL_IC_SC200X) += sc200x_protocol.o
