subdir-ccflags-y += -Werror

obj-$(CONFIG_SCHARGER_V600) += scharger_v600.o
obj-$(CONFIG_SCHARGER_V600) += scharger_v600_base.o
obj-$(CONFIG_SCHARGER_V600) += scharger_v600_direct_charge.o
obj-$(CONFIG_SCHARGER_V600) += scharger_v600_irq.o
