
obj-$(CONFIG_HW_THERMAL_TSENSOR)	+= hw_tsens.o
obj-$(CONFIG_HW_THERMAL_PERIPHERAL)	+= hw_peripheral_tm.o hw_ntc_tm_table.o
obj-$(CONFIG_HW_IPA_THERMAL)	+= hw_ipa_thermal.o
obj-$(CONFIG_HW_IPA_THERMAL)	+= board_cooling.o
obj-$(CONFIG_HW_PERF_CTRL) += thermal_perf_ctrl.o
obj-$(CONFIG_HW_THERMAL_SHELL) += hw_shell_temp.o
obj-$(CONFIG_HW_EXTERNAL_SENSOR) += hw_ipa_sensor.o
obj-$(CONFIG_HW_EXTERNAL_SENSOR_QCOM) += hw_ipa_sensor_qcom.o
