obj-$(CONFIG_HUAWEI_PERF_CTRL)	+= perf_ctrl.o
obj-$(CONFIG_HUAWEI_DDR_PERF_CTRL)	+= ddr_perf_ctrl.o
obj-$(CONFIG_HUAWEI_THERMAL_PERF_CTRL)	+= thermal_perf_ctrl.o
obj-$(CONFIG_HUAWEI_DEV_PERF_CTRL)	+= dev_perf_ctrl.o
obj-$(CONFIG_RENDER_RT) += render_rt.o
