# power drivers
obj-$(CONFIG_HUAWEI_PD) += pd/
obj-$(CONFIG_USB_SWITCH) += switch/
obj-$(CONFIG_ULOG_TRACE) += ulog_trace/
obj-$(CONFIG_CUST_ATTR_GLINK) += cust_attr/
obj-$(CONFIG_HWUSB_EXT_FUNC) += function-huawei/
obj-$(CONFIG_USB_EXTRA_MODEM) += usb_extra_modem/
