#
# Makefile for DUBAI.
#

obj-$(CONFIG_HUAWEI_DUBAI) += \
	dubai.o \
	dubai_wakeup_stats.o

obj-$(CONFIG_HUAWEI_DUBAI_GPU_STATS) += dubai_gpu_freq_stats.o
obj-$(CONFIG_HUAWEI_DUBAI_DDR_STATS) += dubai_ddr_stats.o
