# Makefile for the adsp misc drivers.
obj-$(CONFIG_HUAWEI_QCOM_ADSP_MISC) += awinic_smartamp.o
obj-$(CONFIG_HUAWEI_QCOM_ADSP_MISC) += tfa_smartamp.o
obj-$(CONFIG_HUAWEI_QCOM_ADSP_MISC) += ti_smartamp.o
obj-$(CONFIG_HUAWEI_QCOM_ADSP_MISC) += adsp_misc.o
obj-$(CONFIG_HUAWEI_QCOM_ADSP_MISC) += customize_smartpamp.o
obj-$(CONFIG_HUAWEI_QCOM_ADSP_MISC) += ultrasonic.o
obj-$(CONFIG_HUAWEI_QCOM_ADSP_MISC) += karaoke.o