#=============================================================================
#  wifi
#=============================================================================

obj-$(CONFIG_HW_NETFILTER_MODULE) += hw_netfilter/

obj-$(CONFIG_HW_NETBOOSTER_MODULE) += netbooster/

obj-$(CONFIG_HW_HIDATA_HIMOS) += himos/

obj-$(CONFIG_HUAWEI_BASTET) += bastet/

