# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_HUAWEI_BATTERY_TEMP) += battery_temp.o
obj-$(CONFIG_HUAWEI_MULTI_BATT_TEMP) += multi_bat_temp.o
obj-$(CONFIG_HUAWEI_MULTI_BTB_TEMP) += multi_btb_temp.o
